travis:
  secure:
    BINSTAR_TOKEN: nyWksAjE5cgbrLI+st03NmF7dzQ5cFknN49EL2hWs1FSCV7kMQEP12aLI3j1pIfatAIifvdvV0S7fWpn71BzFrhsWiJzIVxvNsEU+0LOK9KgLsL4oE/WRRMs1gljUNLUqWsfx8HmtniQEyjuoebH3vPDON1sYIwMKuLf/lUwUMxgOEqZTZqeEFBgu5iCdg5gerQeCJLWfyB++wpXtOJ2Z2bZuLTq2+dhq2z0SqZ9bkDoESVtIIT6bSkkJLeelj46wYG4NS12Fhv3q71qPpQGf0P2cVfnRl3A7FAjX+aWuYjMKzAOendRMd8eV7nsWHYJ2rrpmn1qFiWhbQC6wQNt3HGdUmGPks5iM0QJJ9GXKzYgeqweKmYT6+orxQhpaq0f/0vYFPOs4U/MkUjsYJrBWNUzCZQt1nzIk8qxC6xInHGxcKZzOj0XL77n91PYo4jlIV8Qi9r1Oi9SjbZ0ulR1PzdQRgGshp0zMrt4IiNHrOzVyve9ll/4U7mTmY1rxDrHxqVMfndE5360IlcHLNtqK/tiKFGBKlzgKE/SAUamxACw2iC0eVlsrvK0ohkCodYFgxn2B9Wgb6iNbjwrjvHluDzQ8+bQNwo/HJOj2A8guSbqeSnEJiANeDn9aaPHbd2Y1UnLqyEB+x22gifsZNmfO0CbbwCp8Y3vHpiuqLlQ9gU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
